mood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
from mood import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('post.urls')),

    url(r'static/(?P<path>.*)', serve, {'document_root': settings.STATIC_ROOT})
] 

post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.home, name='home'),
    path('new_mood/', views.new_mood, name='new_mood'),
    path('remove_mood/<str:pk>/', views.remove_mood, name='remove_mood'),
    path('edit_mood/<str:pk>/', views.edit_mood, name='edit_mood')
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_avatar/', views.change_avatar, name='change_avatar'),
    path('change_password/', views.change_password, name='change_password'),

]

post/models.py
from django.db import models
from django.contrib.auth import get_user_model

from room.models import Room

# Create your models here.
class ActivePostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Post(models.Model):
    content = models.TextField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
    seen_users = models.ManyToManyField(get_user_model(), related_name='seen_users')
    active = models.BooleanField(default=True)

    objects = models.Manager()
    active_posts = ActivePostManager()

    class Meta:
        ordering = ('-created',)


    def __str__(self):
        return self.content[:100] + '...'

room/models.py
from uuid import uuid4
from django.db import models
# from django.contrib.auth.models import User
from mood.settings import AUTH_USER_MODEL

# Create your models here.

class Room(models.Model):
    uuid = models.UUIDField(default=uuid4())
    name = models.CharField(max_length=255)
    members = models.ManyToManyField(AUTH_USER_MODEL, default=[])

    def __str__(self):
        return f'{self.name} ({self.uuid})'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from room.models import Room

# Create your models here.


class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='static/avatars/%Y/%m/')

post/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages

from .models import Post

# Create your views here.

@login_required
def home(request):

    posts = Post.active_posts.all()
    
    return render(request, 'post/home.html', {
        'posts': posts,
        # 'older_posts': older_posts
    })


@login_required
def new_mood(request):

    if request.method == 'POST':
        content = request.POST['content']

        post = Post.objects.create(
            content=content,
            author=request.user
        )

        messages.success(request, 'Đã thêm mood thành công gòi nè :3')

        

    return render(request, 'post/new_post.html')

@login_required
def remove_mood(request, pk):

    mood = get_object_or_404(Post, pk=pk)
    
    if request.method == 'POST':
        
        mood.active = False
        mood.save()

        messages.success(request, 'Đã xóa mood thành công!')

    return render(request, 'post/remove_post.html', {

    })

@login_required
def edit_mood(request, pk):
    mood = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        content = request.POST['content']
        mood.content = content
        mood.save()

        messages.success(request, 'Đã chỉnh sửa mood thành công!')


    return render(request, 'post/edit_post.html', {
        'mood': mood,
    })

room/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
import os
from datetime import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import get_user_model
from django.urls import reverse

from mood import settings
from post import models as post_models

# Create your views here.

def user_login(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        print(f'>>> {user}')

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('post:home'))
        else:
            messages.error(request, 'Thông tin đăng nhập không chính xác!')
            
        

    return render(request, 'user/login.html', {

    })

def user_logout(request):
    logout(request)

    return HttpResponseRedirect(reverse('user:login'))

@login_required
def profile(request):
    
    moods = post_models.Post.active_posts.filter(author=request.user)
    
    return render(request, 'user/profile.html', {
        'moods': moods,
        'mood_count': moods.count(),
    })

@login_required
def change_avatar(request):
    if request.method == 'POST' and request.FILES['avatar']:
        avatar = request.FILES['avatar']
        
        request.user.avatar = avatar.name

        now = datetime.now()

        year =  now.strftime('%Y')
        month = now.strftime('%m')
        static_dir = os.path.join(settings.BASE_DIR, 'static', 'avatars', year, month)

        fss = FileSystemStorage(static_dir)
        file = fss.save(avatar.name, avatar)

        image_url = os.path.join(settings.STATIC_URL, 'avatars', year, month, avatar.name)

        get_user_model().objects.filter(username=request.user.username).update(
            avatar=image_url
        )

        return HttpResponseRedirect(reverse('user:profile'))

        
    return render(request, 'user/change_avatar.html', {

    })

@login_required
def change_password(request):

    if request.method == 'POST':
        old_password = request.POST['old_password']
        password_1 = request.POST['password_1']
        password_2 = request.POST['password_2']

        user = authenticate(username=request.user.username, password=old_password)
        
        if user is not None:
            if password_1 == password_2:
                user.set_password(password_1)
                user.save()
                return HttpResponseRedirect(reverse('user:logout'))
                
            else:
                messages.error(request, 'Mật khẩu xác nhận không chính xác.')
        else:
            messages.error(request, 'Mật khẩu cũ không chính xác.')

    return render(request, 'user/change_password.html', {

    })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- FAVICON -->
    <link rel="icon" href="{% static 'local_image/mood_favicon.png' %}">

    <!-- BOOTSTRAP 4 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

     <!-- AWESOME ICON -->
     <script src="https://kit.fontawesome.com/07159711c2.js" crossorigin="anonymous"></script>

     <!-- MY CSS -->
     <link rel="stylesheet" href="{% static 'css/my_css.css' %}">

</head>
<body>
    <!-- NAVBAR -->
    {% include  'navbar.html' %}

    <!-- JUMBOTRON -->

    <!-- CONTENT -->
    <div class="container p-0">
        {% block content %}


        {% endblock %}
    </div>

   <!-- FOOTER -->
   {% include 'footer.html' %}
</body>
</html>

templates/footer.html
 <!-- FOOTER -->
<footer class="bg-light text-center mt-2">
    <p class="text-muted">Design by Nguyễn Anh Đô</p>
    <p class="text-muted">Email: nguyenanhdo200213@gmail.com</p>
    <p class="text-muted">Version: 22.07.01</p>
</footer>

templates/jumbotron.html
 <!-- JUMBOTRON -->
<div class="container">
<div class="jumbotron">
    <h1>Mood:3 where to put our moods</h1>
    <p>Ừm! Chào bé, đây là trang web tiên của anh (có thể sử dụng được 🤣). Trước giờ anh toàn code rồi bỏ 
        dở thôi nên không có trang nào ra hồn cả. Chắc là bé chưa biết trang này để làm gì đúng hơm? Khi mà
        có những lời mình ngại nói với nhau trực tiếp trên Messgenger thì mình có thể post trên đây nhá. Trang
        web vẫn còn nhiều chỗ chưa ổn lắm nhưng anh sẽ fix dần dần nè! Iu bé :3
    </p>
</div>

templates/messages.html
<div class="messages">
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger">{{ message }}</div>
            {% elif message.tags == 'success' %}
                <div class="alert alert-success">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

templates/navbar.html
<!-- {% load static %} -->
<nav class="navbar navbar-dark">
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'post:home' %}" class="navbar-brand">
                <img src="{% static 'local_image/mood.png' %}" alt="Logo" width="100">
            </a>
        </div>

        <div class="user">
            <!-- User chưa đăng nhập -->
            {%if not request.user.is_authenticated %}
                <a href="{% url 'user:login' %}" class="btn btn-default text-light" role="button">Đăng nhập</a>

            {% else %}
                <!-- User đã đăng nhập -->
                <div class="dropdown">
                    <img class="avatar dropdown-toggle" data-toggle="dropdown" src="{{ request.user.avatar.url }}" alt="User avatar"> <span class="caret"></span></button>
                    <ul class="dropdown-menu pl-2" style="margin: 2px 0 0 -120px;" >
                      <li><a href="{% url 'post:home' %}">Trang chủ</a></li>
                      <hr>
                      <li><a href="{% url 'user:profile' %}">Tài khoản</a></li>
                      <li><a href="{% url 'user:change_password' %}">Đổi mật khẩu</a></li>
                      <hr>
                      <li><a href="{% url 'user:logout' %}">Đăng xuất</a></li>
                    </ul>
                  </div>
            {% endif %}
           
        </div>
    </div>
</nav>

templates/post/edit_post.html
{% extends 'base.html' %}

{% block title %}Mood | Xóa mood{% endblock %}

{% block content %}
    <!-- EDIT FORM -->
    <div class="container">
        <div class="container mt-2 mb-2">
            <form action="" method="post">

                {% csrf_token %}
                <h4 class="form-text">Chỉnh sửa</h4>
                {% include 'messages.html' %}
                <div class="form-group">
                    <textarea required placeholder="Nói gì đi nè..." class="form-control" name="content"
                     id="content" cols="30" rows="10" >{{ mood.content }}</textarea>
                </div>
                

                <div class="form-group container p-0">
                    <a href="{% url 'post:home' %}" class="btn btn-warning btn-sm" role="button">
                        <i class="fa-solid fa-house-chimney"></i>
                        Trang chủ
                    </a>
                    <button type="submit" class="btn btn-sm btn-primary">
                        <i class="fa-solid fa-floppy-disk"></i>
                        Lưu chỉnh sửa
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/post/home.html
{% extends 'base.html' %}

{% block title %}Mood | Trang chủ{% endblock %}

{% block content %}
    {% include 'jumbotron.html' %}

    <div class="container mt-2 p-0">
        <h2>Moods</h2>
        <a href="{% url 'post:new_mood' %}" class="btn btn-primary" role="button">
            <i class="fa-solid fa-plus"></i>
            Thêm mới mood
        </a>
        {% for post in posts %}
        
            {% include 'post/post.html' with post=post %}

        {% endfor %}
        
        
    </div>


    
{% endblock %}

templates/post/new_post.html
{% extends 'base.html' %}

{% block title %}Mood | New{% endblock %}

{% block content %}
<!-- NEW POST FORM -->
<div class="container">
    <div class="container mt-2 mb-2 p-0">
        
        <form action="" method="post">
    
            {% csrf_token %}
            <h4 class="form-text">Thêm mới</h4>
            {% include 'messages.html' %}
            <div class="form-group">
                <textarea placeholder="Nói gì đi nè (chỉ anh Tóp mỡ mới thấy được)" class="form-control" name="content" id="content" cols="30" rows="10"></textarea>
            </div>
    
            <div class="form-group container p-0">
                <a href="{% url 'post:home' %}" class="btn btn-warning btn-sm" role="button">
                    <i class="fa-solid fa-house-chimney"></i>
                    Trang chủ
                </a>
                <button type="submit" class="btn btn-sm btn-primary">
                    <i class="fa-solid fa-share-from-square"></i>
                    Chia sẻ
                </button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/post/post.html
<div class="card p-2 mt-2">
    <p class="text-muted"><strong>{{ post.created|timesince }} by {{ post.author.get_full_name }}</strong></p>
    <hr>
    <p>{{ post.content|linebreaks}}</p>
    {% if request.user.username == post.author.username %}
    <hr>
    <div class="container p-0 pb-2">
        
        <a href="{% url 'post:remove_mood' pk=post.pk %}" role="button" class="btn btn-sm btn-danger">
            <i class="fa-regular fa-trash-can"></i>
            Xóa bài
        </a>
        <a href="{% url 'post:edit_mood' pk=post.pk %}" role="button" class="btn btn-sm btn-info">
            <i class="fa-solid fa-pen-to-square"></i>
            Chỉnh sửa
        </a>
        <!-- <a role="button" class="btn btn-sm btn-primary">
            <i class="fa-solid fa-eye"></i>
            Xem chi tiết
        </a> -->
    </div>
    {% endif %}
</div>

templates/post/remove_post.html
{% extends 'base.html' %}

{% block title %}Mood | Xóa mood{% endblock %}

{% block content %}
    <div class="container">
        <div class="container pt-2">
            <div class="container text-center">
                <form style="max-width: 100%; width: 400px;" class="card d-inline-block" action="" method="post">
                    {% csrf_token %}
                    <div class="container pb-2">
                        <h3 class="form-text text-center">Xác nhận</h3>
                        {% include 'messages.html' %}
                        <p class="text-warning">Bạn có chắc chắn muốn xóa bài đăng?</p>
                        <button type="submit" class="btn btn-danger btn-block">
                            <i class="fa-regular fa-trash-can"></i>
                            Xác nhận xóa
                        </button>

                        <a href="{% url 'post:home' %}" class="btn btn-primary d-block mt-1" role="button">
                            <i class="fa-solid fa-house-chimney"></i>
                            Trang chủ
                        </a>
                    </div>
                </form>
            </div>
    </div>
{% endblock %}

templates/user/change_avatar.html
{% extends 'base.html' %}

{% block title %}Mood | Profile{% endblock %}

{% block content %}

<!-- AVATAR UPLOAD FORM -->
<div class="container pt-2">
    <div class="container text-center">
        <form style="max-width: 100%; width: 400px;" class="card d-inline-block" 
        action="" method="post" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="container pb-2">
                <h3 class="form-text text-center">Upload ảnh</h3>
                <input required class="form-control mb-2" type="file"  accept=".jpg, .png, .gif, .heic" name="avatar" id="avatar">
                <button type="submit" class="btn btn-primary btn-block">
                    <i class="fa-solid fa-cloud-arrow-up"></i>
                    Lưu
                </button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/user/change_password.html
{% extends 'base.html' %}

{% block title %}Mood | Đổi mật khẩu{% endblock %}

{% block content %}
<div class="container pt-2">
    <div class="container text-center">
        <form style="max-width: 100%; width: 400px;" class="card d-inline-block" action="" method="post">
            {% csrf_token %}
            <div class="container pb-2">
                <h3 class="form-text text-center">Đổi mật khẩu</h3>
                
                {% include 'messages.html' %}
                
                <div class="form-group text-left">
                    <label for="username">Mật khẩu cũ</label>
                    <input  required type="password" name="old_password" id="old_password" class="form-control">
                </div>

                <div class="form-group text-left">
                    <label for="username">Mật khẩu mới</label>
                    <input  required type="password" name="password_1" id="password_1" class="form-control">
                </div>

                <div class="form-group text-left">
                    <label for="username">Nhập lại mật khẩu</label>
                    <input  required type="password" name="password_2" id="password_2" class="form-control">
                </div>

                <button type="submit" class="btn btn-primary btn-block">
                    <i class="fa-solid fa-floppy-disk"></i>
                    Lưu
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block title %}Mood | Đăng nhập{% endblock %}

{% block content %}
    <div class="container text-center mt-2">
        <form class="card" action="" method="post">

            {% csrf_token %}

            <div class="container pb-2">
                <h3 class="form-text text-center">Đăng nhập</h3>
                {% include 'messages.html' %}
                <div class="form-group text-left">
                    <label for="username">Tên đăng nhập</label>
                    <input type="text" name="username" id="username" class="form-control">
                </div>

                <div class="form-group text-left">
                    <label for="password">Mật khẩu</label>
                    <input type="password" name="password" id="password" class="form-control">
                    <small><span class="form-text text-muted text-small">Nhớ tắt caplock nhé!</span></small> 
                </div>

                <button type="submit" class="btn btn-primary btn-block">Đăng nhập</button>
            </div>
        </form>
    </div>

{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}

{% block title %}Mood | Profile{% endblock %}

{% block content %}
    <!-- PROFILE -->
    <div class="container">

        <div class="container card p-2 mt-2">
            <h4>Tài khoản</h4>
            <hr>
            <div class="text-center">
                <img src="{{ request.user.avatar.url }}" style="width: 120px; height: 120px; border-radius: 60px;" alt="User avatar">
                <div></div>
                <a href="{% url 'user:change_avatar' %}" role="button" class="btn btn-default btn-sm mt-1">
                    <i class="fa-solid fa-image"></i>
                    Đổi ảnh đại diện
                </a>
                <h3>{{ request.user.get_full_name }}</h3>
                <p class="m-0">Tên đăng nhập: {{ request.user.username }}</p>
                <p class="m-0">Ngày tham gia: {{ request.user.date_joined }}</p>
            </div>
            <hr>
            
        </div>
    
        <div class="container card p-2 mt-2">
            <h4>Mood đã đăng ({{ mood_count }})</h4>
            <hr>
            {% if mood_count != 0 %}
                {% for mood in moods %}
                    {% include 'post/post.html' with post=mood %}
                {% endfor %}
            {% else %}
                <div class="alert alert-info">Chưa có bài đăng nào</div>
            {% endif %}
        </div>
    </div>
{% endblock %}